### ISSUE TITLE
RGFW Example | More of a question than an issue. 

### ISSUE THREAD

**Issue by ColleagueRiley** [Daivuk/PureDOOM#10]
Could you add an example that uses [RGFW](https://github.com/ColleagueRiley/RGFW)? RGFW is another single-header file library that I created. It's very similar to GLFW in that it only handles basic window management functions and leaves graphics up to the user. 

I've been trying to get the library to work with RGFW, and I have an almost-finished example.

**Comment by ColleagueRiley** [comment]
So this issue is solved now?

**Comment by Daivuk** [comment]
Yup, fixed in one of my recent commits. Thanks for bringing this to my attention.

**Comment by ColleagueRiley** [comment]
> So this issue is solved now?

@Daivuk I put this comment on the wrong issue
