### ISSUE TITLE
.WAD related suggestions and issues 

### ISSUE THREAD

**Issue by ColleagueRiley** [Daivuk/PureDOOM#11]
I have some suggestions for features related to the handling of WAD files

* Look for steam WADs (DOOM 1 + 2 on steam, DOOM 3 .wad folder, DOOM Eternal .wad folder)

* `doom_add_wad_folder`  function

* Add more documentation (in README) about how the program loads and finds .WADs

* Use [FreeDOOM ](https://freedoom.github.io/) as a base .WAD for testing

**Comment by Daivuk** [comment]
I included doom1.wad in the repo, that's a good base for testing. It's the shareware, and it's allowed to distribute it. It's all that's needed test running doom on various devices :)

**Comment by ColleagueRiley** [comment]
Is this new? I didn't see it last time I was testing the repo directly. I completely forgot that episode one was shareware. 

Does PureDoom support wads with different names? When I looked at the code for selecting .wads it had specific file names listed.

**Comment by Daivuk** [comment]
PureDOOM is original source doom, yes it supports different wads. It first attempts to load those wads in order, stops at the first one:
- doom2f.wad
- doom2.wad
- plutonia.wad
- tnt.wad
- doomu.wad
- doom.wad
- doom1.wad (Shareware, free to distribute)

That's for the base game. Then you can load a custom wad using -file in the command line. Those must be documented in many places on the web already, no need I think to repeat it here.

**Comment by ColleagueRiley** [comment]
I don't think the `-file` argument is documented on the readme. It probably should be.

How do you feel about extending the search to include Steam folders? You could also add `doom_add_wad_folder` to allow users to specify specific paths. 

Is there a function to load a wad, so the program can specify the file it wants to use? That would be useful for a wad loading program for example.

**Comment by Daivuk** [comment]
I dont want to replace the original source intent, except for very unfriendly things (Like the bad mouse support I had to fix).
I think what you're looking for is to create a new source port with your ideas, so you could fork this repo and make changes. And PRs are welcomed if its something that's just bad and need fixed. But browser into other folders on your PC is not one of them.

**Comment by ColleagueRiley** [comment]
Okay, I didn't know how strict your project is following the source. 

Adding a `doom_add_wad_folder` function would be good so programs that use the library aren't limited to any given directory set. 

I also plan on creating a non-vanilla source port

**Comment by Daivuk** [comment]
The folder is always the working directory. This shouldn't be needed.

**Comment by ColleagueRiley** [comment]
Or based on an environment variable.  I just think it makes more sense to have it be dynamic, giving the program more options for looking for the file.

**Comment by ColleagueRiley** [comment]
I'm sorry. This issue was made because of a misunderstanding of the nature of the project.
