### ISSUE TITLE
MIDI for linux in example code

### ISSUE THREAD

**Issue by ColleagueRiley** [Daivuk/PureDOOM#16]
Could your SDL example support MIDI calls for Linux instead of only Windows and MacOS?

I plan on looking into this issue, I might create a PR for this later if you don't get to it.

**Comment by Daivuk** [comment]
If you know how, and it doesn't requires crazy amount of setup/thirdparty libs/giant code, then propose a PR with it.
I don't personally run linux. I only have Windows and Mac so I can't debug this.

**Comment by Daivuk** [comment]
Also, wouldn't this kind of thing be distro dependant? Make sure it's toggable with a CMake option if you're not sure it will work on all linux.

**Comment by ColleagueRiley** [comment]
I saw a way of doing it via the Linux API, but it didn't work for me.
It wouldn't be distro dependent, it could be audio driver dependent .

**Comment by Daivuk** [comment]
ya, then it's not great... Windows and Mac have standard MIDI API. I would leave it as is.
