### ISSUE TITLE
Naming conflicts

### ISSUE THREAD

**Issue by ColleagueRiley** [Daivuk/PureDOOM#8]
`LoadMenu` causes an error due to it sharing a name with a WinAPI datatype. 

I was able to fix this by changing each occurrence of `LoadMenu` to `DOOM_LoadMenu`

**Comment by ColleagueRiley** [comment]
For more context, this is happening when I attempt to include the Winapi headers while using the library. 

Although the issue is caused by something on my side, I believe that the library should do more to prevent naming conflicts.

**Comment by Daivuk** [comment]
Thanks for this finding! Feel free to make a PR for it.

**Comment by Daivuk** [comment]
Your PR #9 was merged, but I checked too fast. The change are in the single header file, but original doom files were untouched. So if we run the python script to regen the single header, your changes will get overriden.

**Comment by ColleagueRiley** [comment]
Sorry, I didn't realize the project was organized that way. I'll create a new pull request later today.

**Comment by Daivuk** [comment]
Thanks, I'm trying to create tests and make sure they run on github actions.

**Comment by Daivuk** [comment]
Hi @ColleagueRiley , I am running into the same issue while writing my tests, so I will make the change at the same time.
